server:
  port: 8080
  servlet:
    context-path: /

spring:

  application:
    name: order_server #订单服务

  datasource:
    url: jdbc:mysql://localhost:3306/xiaoshu?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 730730
    driverClassName: com.mysql.jdbc.Driver

  rabbitmq:
    host: 192.168.2.207
    username: admin
    password: 123456
    virtual-host: /
    publisher-confirm-type: correlated  #手动应答


mybatis:
  mapper-locations: classpath:xml/*.xml   #xml扫描
  type-aliases-package: com.model  #resultType 实体类映射

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  notEmpty: true